PYTHONSCRIPTS_VERSION = fce77e1a6a715d152c8bf478f3935b357f4206f5
PYTHONSCRIPTS_SITE = $(call github,rLoopTeam,eng-software-pi,$(PYTHONSCRIPTS_VERSION))
PYTHONSCRIPTS_INSTALL_TARGET = YES
PYTHONSCRIPTS_DEPENDENCIES = linux
PYTHONSCRIPTS_SETUP_TYPE = setuptools

$(eval $(python-package))

