PYTHONSCRIPTS_VERSION = 8e7e682e8fb752349eabd2e8d174402abcd14d7c
PYTHONSCRIPTS_SITE = $(call github,rLoopTeam,eng-software-pi,$(PYTHONSCRIPTS_VERSION))
PYTHONSCRIPTS_INSTALL_TARGET = YES
PYTHONSCRIPTS_DEPENDENCIES = linux
PYTHONSCRIPTS_SETUP_TYPE = setuptools

$(eval $(python-package))

