#!/bin/ash

if ! mount | grep -q "mmcblk0p2" ; then
 echo -e "n\np\n2\n\n\nw\n" | fdisk /dev/mmcblk0
 umount /dev/mmcblk0p1
 hdparm -z /dev/mmcblk0
 mkfs.ext3 -F /dev/mmcblk0p2
 mount /dev/mmcblk0p1
 mount /dev/mmcblk0p2
 cp /etc/wpa_supplicant_sample.conf /mnt/data/wpa_supplicant.conf
 mkdir /mnt/data/config
 echo "New Node" > /mnt/data/config/nodename
 mkdir /mnt/data/pgsql
 chown postgres /mnt/data/pgsql
fi
