#!/bin/sh
#
# start postgresql
#

umask 077

if [ ! -f /mnt/data/pgsql/PG_VERSION ]; then
	echo "Initializing postgresql data base..."
	su - postgres -c '/usr/bin/pg_ctl initdb -D /mnt/data/pgsql'
	echo "done"
fi

start() {
	printf "Starting postgresql: "
	su - postgres -c '/usr/bin/pg_ctl start -w -D /mnt/data/pgsql -l logfile'
	echo "OK"
}
stop() {
	printf "Stopping postgresql: "
	su - postgres -c '/usr/bin/pg_ctl stop -D /mnt/data/pgsql -m fast'
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
