TEENSY_LOADER_CLI_VERSION = f9e6a039f0031569d955fc4e40e02b59e5759007
TEENSY_LOADER_CLI_SITE = $(call github,PaulStoffregen,teensy_loader_cli,$(TEENSY_LOADER_CLI_VERSION))
TEENSY_LOADER_CLI_INSTALL_TARGET = YES
TEENSY_LOADER_CLI_DEPENDENCIES = libusb libusb-compat

define TEENSY_LOADER_CLI_BUILD_CMDS
	$(MAKE) CC="$(TARGET_CC)" LD="$(TARGET_LD)" -C $(@D)
endef

define TEENSY_LOADER_CLI_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/teensy_loader_cli $(TARGET_DIR)/bin
endef

$(eval $(generic-package))
